name: spendwise
description: A simple and smart expense tracker app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Storage
  shared_preferences: ^2.2.2
  provider: ^6.1.0
  get_it: ^7.6.0
  
  # UI & Design
  fl_chart: ^0.69.0
  google_fonts: ^6.1.0
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  
  # Camera & OCR
  image_picker: ^1.0.0
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1
  
  # Utilities
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/app_icon.png
